name: Delete stale branch images

on: 
  delete

jobs: 
  if: github.event.ref_type == 'branch'
  runs-on: self-hosted
  environment: dev
  steps:  
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Extract branch name
      shell: bash
      run: |
          BRANCH_NAME=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | awk 'BEGIN {FS= "/" } ; { print $2 }')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo $BRANCH_NAME
      id: extract_branch

    - name: 'Authenticate to Google Cloud'
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0.6.0'
            
    - name: Login to GAR
      uses: docker/login-action@v3
      with:
          registry: ${{vars.REGISTRY_NAME}}
          username: _json_key #_json_key_base64
          password: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
    
    - name: Delete image tags
      env:
        IMAGE_NAME: ${{vars.REGISTRY_NAME}}/${{vars.PROJECT_ID}}/base-images/pv-app-ecomm-feeds
      run:  |-
           gcloud artifacts docker tags delete $IMAGE_NAME:${{ github.event.ref }}
    