name: Deploy image to Dev env

on:
    pull_request:
      branches: [main]
      types: [closed]

#On PR closure on main -> Pull image with latest tag -> Re-tag image (add dev tag) -> Deploy image to GKE 

env:
    REGISTRY: us-east1-docker.pkg.dev

jobs: 
    Deploy: 
        runs-on: ubuntu-latest
        environment: nprd
        steps:
          
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Extract branch name
            shell: bash
            run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
            id: extract_branch

          - name: 'Authenticate to Google Cloud'
            id: auth
            uses: 'google-github-actions/auth@v1'
            with:
              service_account: ${{ secrets.TERRAFORM_SA }}
              credentials_json: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS }}

          - name: 'Set up Cloud SDK'
            uses: 'google-github-actions/setup-gcloud@v0.6.0'
                 
         
          - name: Login to GAR
            uses: docker/login-action@v3
            with:
                registry: ${{env.REGISTRY}}
                username: _json_key #_json_key_base64
                password: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS}}
          
          
          - name: Configure Docker Client
            run:  |-
                gcloud auth configure-docker --quiet 
        
          - name: Docker images
            run:  |-
                docker images 

          - name: Docker pull
            run:  |-
                docker pull us-east1-docker.pkg.dev/dynamic-circle-398514/ecomm/pv-stores:latest   
          
          - name: Docker images
            run:  |-
              docker images
    
          - name: Retag Docker Image
            env:
                IMAGE_NAME: us-east1-docker.pkg.dev/dynamic-circle-398514/ecomm/pv-stores
            run: |
                COMMIT_HASH=$(git rev-parse --short HEAD)
                docker tag $IMAGE_NAME:latest $IMAGE_NAME-dev 
          
          - name: Docker images
            run:  |-
              docker images

          - name: Docker push
            run:  |-
              docker push us-east1-docker.pkg.dev/dynamic-circle-398514/ecomm/pv-stores-dev:latest


                
