name: Deploy image to Dev env

on:
    pull_request:
      branches: [main]
      types: [closed]

#On PR closure on main -> Pull image with latest tag -> Re-tag image (add dev tag) -> Deploy image to GKE 

env:
    REGISTRY: us-east1-docker.pkg.dev

jobs: 
    Deploy: 
        runs-on: ubuntu-latest
        environment: nprd
        steps:
          
          - name: Checkout Code
            uses: actions/checkout@v3
