name: Deploy image to Dev env

on:
    pull_request:
      branches: [main]
      types: [closed]

env:
    REGISTRY: us-east1-docker.pkg.dev
    CLUSTER_NAME: autopilot-cluster-1 
    CLUSTER_ZONE: us-central1
    PROJECT_NAME: dynamic-circle-398514

jobs: 
    Re-tag: 
        runs-on: ubuntu-latest
        environment: nprd
        steps:
          
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Extract branch name
            shell: bash
            run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
            id: extract_branch

          - name: Authenticate to Google Cloud
            id: auth
            uses: 'google-github-actions/auth@v1'
            with:
              service_account: ${{ secrets.TERRAFORM_SA }}
              credentials_json: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS }}

          - name: Set up Cloud SDK
            uses: 'google-github-actions/setup-gcloud@v0.6.0'
                    
          - name: Login to GAR
            uses: docker/login-action@v3
            with:
                registry: ${{env.REGISTRY}}
                username: _json_key #_json_key_base64
                password: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS}}
          
          
          - name: Configure Docker Client
            run:  |-
                gcloud auth configure-docker --quiet 
        
          - name: Docker images
            run:  |-
                docker images 

          - name: Docker pull
            run:  |-
                docker pull us-east1-docker.pkg.dev/dynamic-circle-398514/ecomm/pv-stores:${{steps.extract_branch.outputs.branch}}  
          
          - name: Docker images
            run:  |-
              docker images
    
          - name: Retag Docker Image
            env:
                IMAGE_NAME: us-east1-docker.pkg.dev/dynamic-circle-398514/ecomm/pv-stores
            run: |
                docker tag $IMAGE_NAME:${{steps.extract_branch.outputs.branch}} $IMAGE_NAME:dev
          
          - name: Docker images
            run:  |-
              docker images

          - name: Docker push
            env:
              IMAGE_NAME: us-east1-docker.pkg.dev/dynamic-circle-398514/ecomm/pv-stores
            run:  |-
              docker push $IMAGE_NAME --all-tags
    
    Deploy:
      needs: Re-tag
      runs-on: ubuntu-latest
      environment: nprd
      steps:  
        - uses: actions/checkout@v3
        - name: Authenticate to Google Cloud
          id: auth
          uses: 'google-github-actions/auth@v1'
          with:
            service_account: ${{ secrets.TERRAFORM_SA }}
            credentials_json: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS }}
       
        - name: Set up Cloud SDK
          uses: 'google-github-actions/setup-gcloud@v0.6.0'

        - name: kubectl - Google Cloud GKE cluster.
          uses: ameydev/gke-kubectl-action@master
          env:
            PROJECT_ID: ${{ env.PROJECT_NAME }}
            APPLICATION_CREDENTIALS: ${{ env.GOOGLE_ACCESS_CREDENTIALS }}
            CLUSTER_NAME: ${{ env.CLUSTER_NAME }}
            ZONE_NAME: ${{ env.CLUSTER_NAME }}
          with:
            args: apply -f first-deployment.yaml
