name: Terraform Deployment for App

on:
    pull_request:
      branches: 
        - 'main'
    
jobs:
  terraform_job_nprod:
    uses: JoaoMariaVizoso/test_public/.github/workflows/reusable_deploy.yml@main
    with:
      env: "org/nprd"
      enviro: nprd
    secrets: inherit

  terraform_job_prod:
    needs: [terraform_job_nprod]
    uses: JoaoMariaVizoso/test_public/.github/workflows/reusable_deploy.yml@main
    with:
      env: "org/prd"
      enviro: prd
    secrets: inherit


