name: Build and Push Image

# This workflow is triggered once a PR is opened
on:
    pull_request:
      branches: [main]

env:
    REGISTRY: us-east1-docker.pkg.dev

jobs: 
    
    ContinuousIntergration:
        if: github.event.review.state != 'approved'
        runs-on: ubuntu-latest
        environment: nprd
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Extract branch name
            shell: bash
            id: extract_branch
            env:
              BRANCH: ${{ github.ref_name}}
            run: |-
                if [[ $input_string == *"/"* ]]; then
                echo "::set-output name=fragment::${BRANCH##*/}" >> $GITHUB_OUTPUT
                else
                echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
                fi
                           

          - name: 'Authenticate to Google Cloud'
            id: auth
            uses: 'google-github-actions/auth@v1'
            with:
              service_account: ${{ secrets.TERRAFORM_SA }}
              credentials_json: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS }}

          - name: 'Set up Cloud SDK'
            uses: 'google-github-actions/setup-gcloud@v0.6.0'
                 
         
          - name: Login to GAR
            uses: docker/login-action@v3
            with:
                registry: ${{env.REGISTRY}}
                username: _json_key #_json_key_base64
                password: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS}}
          
          
          - name: Configure Docker Client
            run:  |-
                gcloud auth configure-docker --quiet 
        
          
          - name: Build Docker Image
            env:
                IMAGE_NAME: us-east1-docker.pkg.dev/dynamic-circle-398514/ecomm/pv-stores
            run: |
                COMMIT_HASH=$(git rev-parse --short HEAD)
                docker build -t $IMAGE_NAME:${{ steps.extract_branch.outputs.fragment }}-$COMMIT_HASH .
            
            
          - name: Push Docker Image to GAR
            env: 
                IMAGE_NAME: us-east1-docker.pkg.dev/dynamic-circle-398514/ecomm/pv-stores
            run: |-
                docker push $IMAGE_NAME --all-tags
    




                