---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: whereami-deployment
    namespace: dev
  spec:
    selector:
      matchLabels:
        app: whereami
    template:
      metadata:
        labels:
          app: whereami
      spec:
        containers:
        - name: whereami
          #image: northamerica-northeast2-docker.pkg.dev/pv-sharedsvcs-npd-sre-f641/pv-app-ecomm/whereami:v1.2.6
          image: gcr.io/google-samples/whereami:v1.2.6
          ports:
          - containerPort: 8080
          livenessProbe: #There is a health probe listening on port 8080/healthz that will respond with 200 if the application is running
            httpGet:
                path: /healthz
                port: 8080
                scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 10
---
  apiVersion: v1
  kind: Service
  metadata:
    name: whereami-service
    namespace: dev
    annotations:
      cloud.google.com/neg: '{"ingress": true}'
      #cloud.google.com/neg: '{"exposed_ports":{"10000":{}}}'
      #beta.cloud.google.com/backend-config: '{"default": "healthcheck-whereami"}'
  spec:
    #type: NodePort 
    selector:
      app: whereami
    ports:
    - protocol: TCP
      port: 10000 
      targetPort: 8080
 

