name: Build and Push Image - BE

# This workflow is triggered once a PR is opened
on:
    pull_request:
      branches: [main]

env:
    REGISTRY: us-east1-docker.pkg.dev

jobs: 
    
    Build:
        runs-on: ubuntu-latest
        environment: nprd
        permissions: 
            contents: read
            packages: write
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: 'Authenticate to Google Cloud'
            id: auth
            uses: 'google-github-actions/auth@v1'
            with:
              service_account: ${{ secrets.TERRAFORM_SA }}
              credentials_json: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS }}
                 
          - name: Login to GAR
            uses: docker/login-action@v3
            with:
                registry: ${{env.REGISTRY}}
                username: _json_key #_json_key_base64
                password: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS}}



