name: Build and Push Image - BE

# This workflow is triggered once a PR is opened
on:
    pull_request:
      branches: [main]

env:
    REGISTRY: us-east1-docker.pkg.dev

jobs: 
    
    Build:
        runs-on: self-hosted
        environment: nprd
        permissions: 
            contents: read
            packages: write
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: 'Authenticate to Google Cloud'
            id: auth
            uses: 'google-github-actions/auth@v1'
            with:
              service_account: ${{ secrets.TERRAFORM_SA }}
              credentials_json: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS }}
                 
          - name: Login to GAR
            uses: docker/login-action@v3
            with:
                registry: ${{env.REGISTRY}}
                username: _json_key #_json_key_base64
                password: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS}}





#            - name: Build Docker Image
#                env:
#                IMAGE_NAME: linux_tweet_app #create env called IMAGE_NAME consisted of actual name of Docker Image after we build
#                PROJECT_ID: service-project-ardhan-1
#                run: docker build -t $IMAGE_NAME:latest . #build the docker image
#                
#            - name: Configure Docker Client
#                run:  |-
#                gcloud auth configure-docker --quiet #authenticate to gcr
#            
#            - name: Push Docker Image to Container Registry GCR
#                env: 
#                IMAGE_NAME: linux_tweet_app
#                PROJECT_ID: service-project-ardhan-1
#                #tag docker image to gcr image format then push to gcr
#                run: |-
#                docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest 
#                docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest 
#                
#            - name: Extract metadata (tags, labels) for Docker GHCR
#                env:
#                REGISTRY: ghcr.io
#                IMAGE_NAME: ${{ github.repository }}
#                id: meta
#                uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#                with:
#                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} #create ghcr image format within as id called meta
#            
#            - name: Build and push Docker image
#                uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc #push docker image to ghcr
#                with:
#                context: .
#                push: true
#                tags: ${{ steps.meta.outputs.tags }}
#                labels: ${{ steps.meta.outputs.labels }}