name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

jobs:
  terraform-apply:
    environment:  nprd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9  # Replace with your desired Terraform version

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{ vars.TERRAFORM_SA }}
          credentials_json: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS }}
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0.6.0'
      - name: Choose Terraform Plan
        id: select-plan
        run: |
          # Use GitHub API to list artifacts from the latest run of the Terraform Plan workflow
          latest_run_id=$(gh api "repos/${{ github.repository }}/actions/workflows/Terraform%20Plan/runs" | jq -r '.workflow_runs[0].id')
          artifacts=$(gh api "repos/${{ github.repository }}/actions/runs/${latest_run_id}/artifacts" | jq -r '.artifacts[].name')
          echo "::set-output name=plan::${artifacts}"
        shell: bash

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: ${{ steps.select-plan.outputs.plan }}
          path: ./tfplan

      - name: Apply Terraform Plan
        run: |
          cd org/nprd
          terraform init 
          terraform apply --var-file='env.tfvars' -auto-approve tfplan
