name: Terraform Plan

on:
  push:
    branches:
      - main  # Replace with the branch you want to monitor for changes

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9  # Replace with your desired Terraform version

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{ vars.TERRAFORM_SA }}
          credentials_json: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS }}
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0.6.0'

      - name: Terraform Plan
        run: |
          cd org/nprd
          terraform init
          terraform plan --var-file='org/nprd/env.tfvars' -out=tfplan
        id: plan

      - name: Save Terraform Plan as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: ./tfplan