name: Terraform Plan

on:
  push:
    branches:
      - main  # Replace with the branch you want to monitor for changes

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Replace with your desired Terraform version

      - name: Terraform Plan
        run: |
          cd org/nprd
          terraform init
          terraform plan --var-file='org/nprd/env.tfvars' -out=tfplan
        id: plan

      - name: Save Terraform Plan as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: ./tfplan