# To use this workflow the following secrets should be stored in GH:
#       TERRAFORM_SA
#       GOOGLE_APPLICATION_CREDENTIALS

name: Terraform Setup and Plan 

# This workflow is triggered once a PR is opened
on:
    push:
      branches-ignore:    
      - 'main'


# Define Terraform Version and directory where it will run
env: 
  TERRAFORM_VERSION: "1.2.9"
  TF_DIRECTORY: "org/nprd"

jobs: 
  terraform_plan:
    runs-on: ubuntu-latest
    environment: nprd
       
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get Directory Name 
        id: dir-id
        shell: bash
        env:
          DIRECTORY: ${{ env.TF_DIRECTORY}}
        run: | 
          DIR_NAME=$(echo $DIRECTORY | awk 'BEGIN {FS= "/" } ; { print $2 }')
          echo "DIR_NAME=$DIR_NAME" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{ vars.TERRAFORM_SA }}
          credentials_json: ${{ secrets.GOOGLE_ACCESS_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0.6.0'

      - name: Terraform Init
        id: init
        working-directory: ${{ env.TF_DIRECTORY}}
        shell: bash
        run: |
          terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TF_DIRECTORY}}
        shell: bash
        run: |
          echo 'plan<<EOF' 
          terraform plan -no-color -out=tfplan 
          echo 'EOF' 

      - name: Save Artifact
        id: save-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.dir-id.outputs.DIR_NAME }}-${{github.event.push.number}}-tf-plan
          path: ${{ env.TF_DIRECTORY}}/tfplan
